#!/bin/bash

export MANGA_SPECTRO=.
export VERSDRP=v1_0_0
export MANGA_SPECTRO_REDUX=$MANGA_SPECTRO/redux/$VERSDRP
export VERSDAP=v0_9_0
export MANGA_SPECTRO_ANALYSIS=$MANGA_SPECTRO/analysis/$VERSDAP
export MANGA_DAP_DIR=$MDAP_DEV

return 0

